import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";

const html = readFileSync("output/local-review/index.html", "utf8");
const js = readFileSync("output/local-review/assets/app.js", "utf8");
const css = readFileSync("output/local-review/assets/styles.css", "utf8");

assert(html.includes("Reactive Site Distribution"), "summary histogram title should use requested copy");
assert(html.includes("Reactive Compound Selectivity"), "compound selectivity title should use requested copy");
assert(js.includes("setDatasetLoading("), "dataset switch should expose loading state while async render work runs");
assert(js.includes("TMT SN"), "raw hover label should say TMT SN");
assert(js.includes("tooltip-stats one-row"), "R/P-value/Sites Hit should render as a one-row stats block");
assert(js.includes("computeTooltipPosition"), "hover positioning should reserve collision space before placing");
assert(css.includes(".plot .svg-container"), "Plotly containers should be forced to fill the panel width");
assert(css.includes(".dataset-toggle.loading"), "dataset switch should have a visible loading state");
assert(css.includes(".tooltip-stats.one-row"), "tooltip one-row stats should have dedicated layout CSS");
assert(html.includes('id="summaryDetailModal"'), "summary click details should have a shared modal");
assert(html.includes('id="dropNoReplicates"'), "dataset controls should expose the no-replicate compound filter");
assert(js.includes('plot.on("plotly_click"'), "summary plots should bind Plotly click events");
assert(js.includes("showCompoundBinModal"), "compound summary bars should open compound structure details");
assert(js.includes("showSiteBinModal"), "site distribution bars should open readable site details");
assert(js.includes("showSiteHitsTooltip"), "site hit donut should use the custom white tooltip");
assert(js.includes("showCompoundSummaryTooltip"), "summary compound charts should use compact custom hover text");
assert(js.includes("Click to see all sites"), "site distribution hover should point users to click details");
assert(js.includes("Click to see all compounds"), "compound chart hovers should point users to click details");
assert(js.includes("sites (${roundLabel(payload.percent, 1)}%)"), "site hit donut hover should read N sites (%)");
assert(js.includes("${escapeHtml(payload.title)} (${Number(payload.sites?.length || 0).toLocaleString()} sites)"), "site distribution hover should read percent first, then site count");
assert(js.includes("compounds</div>"), "compound chart hover should read N compounds without Plotly hover labels");
assert(js.includes("sort: false"), "site hit donut slices should preserve label/value order for hover labels");
assert(js.includes("No interactors found from PDB structures"), "empty interactor dropdown should use requested wording");
assert(!js.includes("No structural contacts found."), "redundant no-contact message should be removed");
assert(js.includes("Site rank:"), "compound point hovers should show site rank rather than site hit count");
assert(!js.includes("R-${payload.rRank"), "compound point rank should not include the old R- prefix");
assert(js.includes('title: "log\\u2082R"'), "volcano x axis should use subscript 2 with no space before R");
assert(js.includes('title: "-log\\u2081\\u2080P"'), "volcano y axis should use subscript 10 with no space before P");
assert(!js.includes('legend: { title: { text: "Selectivity" } }'), "compound selectivity legend should not have a title");
assert(js.includes("state.compoundChoiceCountCache.clear()"), "filter changes should invalidate compound choice count labels");
assert(js.includes("noReplicateDrugs"), "manifest no-replicate metadata should be wired into compound filters");
assert(js.includes("updateDatasetStatus"), "dataset status should reflect the no-replicate filter state");
assert(js.includes("globalOverlayTrace(cancerHighlighted"), "global proteome should draw cancer overlays below custom and hits");
assert(js.includes("globalOverlayTrace(customHighlighted"), "global proteome should draw custom overlays below hits");
assert(js.includes("globalOverlayTrace(hitHighlighted"), "global proteome should draw hit overlays on top");
assert(css.includes(".viewer-meta"), "site structure source/message rows should share an aligned meta row");
assert(css.includes(".tooltip-compact-value"), "compact summary hovers should have centered text styling");
assert(css.includes(".molecule-tooltip.compact-tooltip"), "compact summary hovers should remove excess horizontal whitespace");
assert(js.includes("domain: { x: [0, 0.82]"), "site hit donut should be enlarged within its card instead of shrinking the card");
assert(js.includes("margin: { l: 52, r: 2, t: 4, b: 58 }"), "compound summary plots should use reduced internal bottom margin");
assert(js.includes("dynamicCompoundHitCounts") && js.includes("await yieldToBrowser()"), "compound dropdown count refresh should run in cancellable browser-yielded batches");
assert(js.includes('el("compoundThreshold").addEventListener("input"') && js.includes("await updateSelectedCompoundChoiceLabel()") && js.includes("scheduleCompoundChoiceListRefresh({ invalidate: false })"), "compound threshold changes should update the selected label immediately and rebuild the full list asynchronously");
assert(html.includes('id="compoundRefreshList"'), "compound controls should expose a manual refresh-list action next to the label");
assert(html.includes("<em>Update list</em>"), "manual compound list update should be italicized");
assert(css.includes(".field-label-row") && css.includes(".inline-refresh"), "manual refresh action should align with the compound label");
assert(js.includes("refreshCompoundChoiceList"), "manual refresh action should rebuild compound dropdown counts on demand");
assert(js.includes("const updated = await populateCompoundChoices(activeRefreshToken)") && js.includes("if (updated) await renderCompound()"), "manual refresh should use the same select rebuild path as compound filters");
assert(js.includes("qualityPassFromCompoundSnapshot"), "dynamic compound hit counts should use a stable filter snapshot during async loads");
assert(js.includes("PROTEOME_MUTED_GREY"), "compound plots should use the same muted grey as proteome explorer");
assert(js.includes("size: 46"), "global proteome overlays should have a large hover-capture layer");
assert(js.includes("hoverdistance: 40"), "global proteome should prefer nearby overlay hover targets");
assert(js.includes('name: "Protein clusters"') && js.includes('hoverinfo: "none"'), "global proteome background points should remain hoverable while overlay targets sit above them");
assert(css.includes(".site-analysis-layout > .panel"), "site analysis sidebar and plot panels should have dedicated height controls");
assert(css.includes("min-height: 480px"), "site bar plot should be shorter to align with the sidebar box");
assert(html.includes("compound-plot-panel") && css.includes(".compound-plot-panel #compoundScatter") && css.includes("min-height: 360px"), "compound plots should have shorter matching plot boxes");
assert(js.includes("height: 380"), "compound engagement and volcano Plotly layouts should render shorter SVGs");
assert(js.includes('tooltip.classList.add("hit-tooltip")'), "summary and site bar hovers should use the larger hit tooltip image treatment");
assert(css.includes(".molecule-tooltip.hit-tooltip img") && css.includes("max-height: 144px"), "hit tooltip compound images should be 50 percent larger");
assert(css.includes(".site-analysis-layout") && css.includes("margin-bottom: 16px") && css.includes(".site-structure-panel") && css.includes("margin-top: 0"), "site structure panel should have one standard 16px gap above it");
assert(html.includes("Protein structure"), "structure selector label should use requested wording");
assert(html.includes("Intermolecular interactors"), "contact selector label should use requested wording");
assert(html.includes("<h2>Engagement profile</h2>"), "compound scatter heading should use requested casing");
assert(html.includes('<h2 class="section-gap">Volcano plot</h2>'), "volcano heading should use requested casing");
